spring.application.name=wpBot

# Multipart dosya yükleme ayarları
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Sunucu Base URL (Lokal geliştirme için localhost, canlı ortam için sunucu IP)
# Lokal:  http://localhost:8080
# Canlı:  http://94.130.231.165:8080
app.server.url=http://localhost:8080
